### ISSUE TITLE
change default time expire

### ISSUE THREAD

**Issue by shins5kai** [sebsauvage/ZeroBin#106]
hello,

Where I can change the time default expiration ?

**Comment by elrido** [comment]
You need to change the `selected` expiration time [in the template](https://github.com/sebsauvage/ZeroBin/blob/master/tpl/page.html#L57).

If you want to change what times are offered, you also need to change the [validation logic](https://github.com/sebsauvage/ZeroBin/blob/master/index.php#L179).

**Comment by shins5kai** [comment]
ok thanks :)
