### ISSUE TITLE
Update README ASAP

### ISSUE THREAD

**Issue by matunixe** [sebsauvage/ZeroBin#112]
As this software isn't maintained anymore please update the README to provide some infos. It will be nice to find the name of the fork : https://privatebin.info and some security advices regarding the actual state of the code.
I saw a lot of projects hosting ZeroBin instances while it's not secure at all.

Many thanks.

**Comment by rugk** [comment]
And there is also a PR for that: https://github.com/sebsauvage/ZeroBin/pull/107

**Comment by ghost** [comment]
It's done. Thanks.
