### ISSUE TITLE
Show dislaimer step on Burn After Reading consultation

### ISSUE THREAD

**Issue by fpeyraud** [sebsauvage/ZeroBin#113]
When pasting links through instant messaging system such as slack, which automatically tries to include a preview of the link, the text may be disclosed and the data will be destroyed before the recipient can access it. As an example, 1ty.me adds an extra step before displaying the paste.

**Comment by elrido** [comment]
This was resolved in [August 2015](https://github.com/elrido/ZeroBin/issues/11) in the maintained fork [PrivateBin](https://github.com/PrivateBin/PrivateBin): The pastes only get deleted after successful decryption.

**Comment by fpeyraud** [comment]
Thanks
