### ISSUE TITLE
PRNG

### ISSUE THREAD

**Issue by haypo** [sebsauvage/ZeroBin#62]
The SJCL library implements Fortuna's PRNG (random number generator) which requires a lot of entropy, but SJCL only uses two weak source of entropy: current time and (x,y) of the mouse when the cursor is moved. More and better entropy sources should be used, or another PRNG should be used.

A browser does not offer a PRNG or a CPRNG?

See also issue #37.

**Comment by WAR10CKfreeworld** [comment]
What about the SecureRandom function in JavaScript?

**Comment by vstinner** [comment]
Issue reported 3 years ago, no update since 1 year. I just close it :-)

**Comment by rugk** [comment]
Yes, better switch to https://privatebin.info/.
