### ISSUE TITLE
Force no-cache

### ISSUE THREAD

**Issue by Salokyn** [sebsauvage/ZeroBin#94]
I use nginc proxy-cache on my web server. Though ZeroBin should not be cashed because deleted messages will continue to be available till the cache expires.
Could you add some headers to control cashing like those :

header("Cache-Control: no-cache, no-store, must-revalidate"); // HTTP 1.1.
header("Pragma: no-cache"); // HTTP 1.0.
header("Expires: 0"); // Proxies.

**Comment by elrido** [comment]
FYI: In the [current release](https://github.com/elrido/ZeroBin/releases/tag/0.21.1) of the fork we provide [these headers in the HTML output](https://github.com/elrido/ZeroBin/blob/9f68658106b583afbebeb50972b208de2bc35798/lib/zerobin.php#L608).

**Comment by Salokyn** [comment]
Ok, but it seems not to work.

See by yourself : https://www.gifino.fr/ZeroBin/?f246a9489f7f20be#Z9JVMZpQ02oHR644dBMb+1w+Li3JFfSyEL6VQf8S/0w=
(my cache is valid during 24h)

Those headers are not received and I get a 'X-cache: "HIT"'

**Comment by Salokyn** [comment]
Oh sorry, I hadn't noticed you made a fork. I am using sebsauvage's 0.19 version.

**Comment by Salokyn** [comment]
Thank you ! I will upgrade to this new version.
